# マウスでペイン選択・リサイズを可能にする
set -g mouse on

# ステータスライン左側のセッション名の最大値を伸ばす
set-option -g status-left-length 20
# ステータスライン右側のホスト名と時刻を消去
set-option -g status-right ""

# Escキーの遅延を解消
set -sg escape-time 10

# 現在ペインが Vim/Neovim かどうかを判定する
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\/)?g?(view|n?vim?x?)(diff)?$'"
# Vim/Neovim ならキーを渡し、そうでなければ tmux ペイン移動として扱う
# vim-tmux-navigator プラグインとセットにして、同じキーバインドでシームレスに移動できる
bind-key -n C-h if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n C-j if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n C-k if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n C-l if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'